# pre-commit install
# pre-commit install --hook-type commit-msg
# pre-commit autoupdate
# pre-commit run --all-files
# pre-commit run --files "sys_setup/windows/main.py"

# More info about conventional commits here:
# https://gist.github.com/joshbuchea/6f47e86d2510bce28f8e7f42ae84c716

repos:
  # 🍑 Basic ones
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: check-ast
      - id: check-docstring-first
      - id: check-toml
      - id: check-xml
      - id: check-yaml
      - id: check-builtin-literals
      - id: check-byte-order-marker
      - id: check-executables-have-shebangs
        types: [markdown, python]
        files: "\\.(md|py)$"

  # 🍑 Conventional commits
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v3.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [] # Opt: list of Conv Commits types to allow like: ci,fix..

  # 🍑 Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.6
    hooks:
      - id: ruff-format # Formats code
      - id: ruff # Lints code
        types_or: [python, pyi, jupyter]

  # 🍑 Notebooks
  - repo: local
    hooks:
      - id: jupyter-nb-clear-output
        name: jupyter-nb-clear-output
        files: \.ipynb$
        stages: [commit]
        language: system
        entry: jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace
