[tool.poetry]
name = "lifetracking"
version = "0.3.0"
description = ""
authors = ["None"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<4"
rich = "^13.3.5"
pandas = "^2.0.1"
prefect = "^2.10.9"
isort = "^5.12.0"
browser-history = "^0.3.2"
requests = "^2.31.0"
ankipandas = "^0.3.14"
geopandas = "^0.13.0"
contextily = "^1.3.0"
ffmpeg-python = "^0.2.0"
meteostat = "^1.6.5"
pydub = "^0.25.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.1"
black = "^23.3.0"
pre-commit = "^3.3.1"
tomlkit = "^0.11.8"
pydocstyle = "^6.3.0"
json5 = "^0.9.11"
coverage = "^7.2.5"
hypothesis = "^6.75.3"
flake8 = "^6.0.0"
ipykernel = "^6.23.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
