name: Python package

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false # if one job fails, the other jobs will not be cancelled
      matrix:
        operating-system: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - name: Print environment variables
        run: |
          echo "GITHUB_ACTIONS: ${{ env.GITHUB_ACTIONS }}"

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install poetry
          poetry install

      - name: Check with black
        run: |
          poetry run black --check .

      - name: Check with isort
        run: |
          poetry run isort --check-only .

      - name: Lint with flake8
        run: |
          # Old
          # stop the build if there are Python syntax errors or undefined names
          # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Mine
          poetry run flake8 . --count --max-complexity=10 --max-line-length=88 --statistics --ignore=F401,W503,E203

      - name: Test with pytest
        run: |
          # I'm not sure about disabling the tests, but it's in for now!
          poetry run pytest --disable-pytest-warnings
